apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: gke-cicd-pipeline
spec:
  targets:
    - dev
  # profiles:
  # - dev
  # - targetId: staging
  #   profiles:
  #   - staging
  targetId: 
    - prod
  #   profiles:
  #   - prod
